### ISSUE TITLE
Support safe playback of reference and stimuli of different length

### ISSUE THREAD

**Issue by faroit** [audiolabs/webMUSHRA#12]
Currently when the reference and the stimuli have a different number of samples an error is thrown and if `stopOnErrors: true` is set, experiments will not be started.

If experiments are started nonetheless webMUSHRA behaves as followed:
* the size of the output buffer is determined by the length of the reference
* when the reference is __shorter__ than then a stimulus, the stimuli will be trimmed to the length of the reference. this does not affect playback.
* when the reference is __longer__ than a stimulus, the buffer might be filled up with undefined memory content, resulting in weird output on some browsers.

The expected behaviour in this case would be that the stimuli are filled up/padded with silence. Even though we decided earlier to force users to make sure that references and stimuli have the same length;  user feedback shows that this fix would increase the usability for many users.

**Comment by faroit** [comment]
just looked a bit in the code, my guess would be that the problem is somewhere here:

https://github.com/audiolabs/webMUSHRA/blob/master/lib/webmushra/audio/MushraAudioControl.js#L277

what do you think?

**Comment by mschoeffler** [comment]
Yes, in case the stimuli have different lengths, the code will crash here. As you wrote, an error is thrown, since this is the intended behavior -- at least for now. 
In my opinion, the constructor of MushraAudioControl is a good place for adding the auto-trimming/padding. It has to be checked, whether the lengths are different. If a stimulus is different than the reference, we need to create a new audio buffer object and (probably) delete the old one (attributes of AudioBuffer are read-only https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer => can't be modified).

**Comment by faroit** [comment]
> (attributes of AudioBuffer are read-only https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer => can't be modified).

uh okay I didn't know about this. Than it makes sense to copy the buffers around.

**Comment by faroit** [comment]
this is addressed by #14
