### ISSUE TITLE
How to build a crowd-sourced listening test by webMUSHRA?

### ISSUE THREAD

**Issue by jundengdeng** [audiolabs/webMUSHRA#20]
First of all, thanks for releasing this cool tool for listening test.
webMUSHRA works so great locally and I believe it works for a crowd-sourced listening test.  But the current README doesn't explain it.  Can you please elaborate it? Thanks!

And there are more questions: where does it save the ratings from multiple users? How does it differ the ratings of different users? Using different csv files?

Thanks a lot and best regards,

Jun

**Comment by mschoeffler** [comment]
Hi Jun, 
in order to use webMUSHRA for crowd-sourced listening tests, you have to deploy it on a webserver. Basically, the procedure is the same as running it locally, except that your webserver is accessible by a domain, static ip, etc. Please, let me know if you need more information here. 
When you carry out a listening test, you can find all ratings in the "results" folder. The file structure is "results/NAME_OF_YOU_EXPERIMENT/NAME_OF_PAGE_TYPE.csv". The ratings from multiple users are stored in the same file. If you added the finish page to your experiment, the participant is asked to enter his or her email address. If everything worked correct, you can find this email address in a column of the csv file.

**Comment by ronggong** [comment]
Thanks for the webMUSHRA!

I deployed webMUSHRA on an aws ec2 server. Php is also installed. here is the link:
http://ec2-13-250-5-77.ap-southeast-1.compute.amazonaws.com/webMUSHRA/webMUSHRA/?config=daxp_Qing_zao_qi_lai-Mai_shui-dxjky.yaml

The problem happens after I finished the test and clicked "send results". No error reported, however, I can't see any folder generated in my webMUSHRA folder on the EC2 server?

This has been tested locally, which successfully created the result folder.
