### ISSUE TITLE
How to make it support stereo wav file?

### ISSUE THREAD

**Issue by masterzdj** [audiolabs/webMUSHRA#32]
I have to say this is a great project. Thanks for the developers.

One small question, this project seems not support play stereo wav file. How to make it happen? thanks.

**Comment by faroit** [comment]
Webmushra supports up to 8 channels. Just make sure both reference and stimuli are in the same channel configuration

**Comment by masterzdj** [comment]
thanks for your quickly relpy, faroit.
i know the problem. when i start the test, i can see the waveform of the stereo file, but there is no sound when i press 'play' button. when i jump to the next test item groups, and jump back. the stereo file can be played correctly.

**Comment by masterzdj** [comment]
another problem is that, for mono test items, i can only hear the sound from the left speaker, not both speakers.

**Comment by faroit** [comment]
The mono behavior is known, indeed and is a browser issue as far as I remember. Please render your stimuli as stereo files.

**Comment by faroit** [comment]
Can we close this?

**Comment by DrWig** [comment]
no, don't close this.  There is a bug mentioned in this thread which is still an issue.  If you don't include a page without audio for page one, audio doesn't work.  This is true of the example configs currently.

**Comment by faroit** [comment]
@masterzdj @DrWig please report the exact config file and the browser/OS so that I can test.
Again, webMUSHRA renders all input channels from the stimulus to the output device. If your input has only one channel, the output will also be rendered for for just one channel. If you have different channel configurations for different stimuli, the reference stimulus has higher priority.

We don't think that we should change this behaviour since any kind of downmix or upmix can have an effect on the perceived output quality. Therefore we leave this up to the experimenter design.

**Comment by faroit** [comment]
> no, don't close this. There is a bug mentioned in this thread which is still an issue.

@DrWig please open a new issue that is addressing the mono issue.

**Comment by DrWig** [comment]
ah, ok....apologies.  Fast response, though!

**Comment by faroit** [comment]
@DrWig can this be closed?
