### ISSUE TITLE
How to use only several randomly selected pages?

### ISSUE THREAD

**Issue by LordOfLuck** [audiolabs/webMUSHRA#36]
I need to evaluate 4 different speech synthesis systems.
I have 100 sentences and I have synthesized audio of each sentence from each TTS system.
The users should evaluate a sentence generated by all systems with mushra method, but I do not want a single user to have to go through 100 tests. Is it possible to randomly select eg. 10 pages that would be presented to the user?

**Comment by faroit** [comment]
@LordOfLuck I think the easiest way to implement this is to generate and serve the config files dynamically using e.g. python flask so that users will get a random experiment presented. Doing this externally also gives you more control over how to save the results (e.g. in a centralized db instead of plain files)
