### ISSUE TITLE
[bug] Audio plays only in left speaker

### ISSUE THREAD

**Issue by iver56** [audiolabs/webMUSHRA#55]
When I visit https://audiolabs.github.io/webMUSHRA/ and play the reference audio, I can only hear the audio in the left speaker. I find this behavior in both Chrome and Firefox. I want to have the audio in both speakers.

**Comment by iver56** [comment]
Closing as duplicate of https://github.com/audiolabs/webMUSHRA/issues/53

Why is this the expected behavior though? It feels like a bug more than an intended feature.

**Comment by faroit** [comment]
> Why is this the expected behavior though? It feels like a bug more than an intended feature.

because any kind of up- or downmixing (especially when using a non-standard channel mapping) can have a severe impact on the perceptual quality. Imagine the reference is mono but one of the signals under test is stereo: we can't assume that the experimental design was designed so that the increased loudness of the upmixed mono signal was really taken into account.  Thats why we think the only solution here is to leave this decision to the experimenter only and we explicitly set the `channelInterpretation` to  `"discrete"`. 

Of course, it would be safe to support mono -> stereo by just duplicating channels, but there are a lot of cases that would have to be supported not being part of the [standard](https://developer.mozilla.org/en-US/docs/Web/API/AudioNode/channelInterpretation).

In any case, maybe this should be documented in a better way. Feel free to reopen if you have an idea how to document

**Comment by iver56** [comment]
Thanks for the response! Automatically playing mono as stereo (by duplicating the channels) does indeed seem like a safe (and common-sense) default, as that's how most audio players work, and it's how most people listen to audio.

If it was up to me, I would rather change the default for mono files than document the way mono audio is currently played back in the web app. Users that require special mono interpretation (i.e. play it back only on the first channel) would have to set a config variable.

**Comment by faroit** [comment]
> Automatically playing mono as stereo (by duplicating the channels) does indeed seem like a safe (and common-sense) default, as that's how most audio players work, and I think that's what most listeners expect.

when we developed webmushra we carried out a lot of loudspeaker listening experiments involving specific speaker setups. Among them was also just a single loudspeaker, so its not that uncommon. ;-)

> If it was up to me, I would rather change the default for mono files than document the way mono audio is currently played back in the web app. Users that require special mono interpretation (i.e. play it back only on the first channel) would have to set a config variable.

I would be okay to change the default for mono values __if both, the reference and all stimulus__ are mono. If there is any constellation of heterogeneous stimulus, it would be safer to throw an exception for reasons given above.

I won't have time implementing this, so feel free to open a PR or reopen this issue so that this is documented for future users.
